import streamlit as st

from core import (
    exchange_auth_code_for_session,
    set_auth_session,
    update_authenticated_user_password,
)


st.set_page_config(
    page_title="Set Password",
    page_icon=":material/lock_reset:",
    layout="centered",
)


def _establish_password_setup_session() -> dict[str, str] | None:
    if st.session_state.get("password_setup_user"):
        return st.session_state["password_setup_user"]

    query_params = st.query_params
    code = str(query_params.get("code", "") or "").strip()
    access_token = str(query_params.get("access_token", "") or "").strip()
    refresh_token = str(query_params.get("refresh_token", "") or "").strip()

    try:
        if code:
            st.session_state["password_setup_user"] = exchange_auth_code_for_session(code)
            query_params.clear()
            return st.session_state["password_setup_user"]
        if access_token and refresh_token:
            st.session_state["password_setup_user"] = set_auth_session(access_token, refresh_token)
            query_params.clear()
            return st.session_state["password_setup_user"]
    except Exception as exc:
        st.error(f"Could not verify the password setup link: {exc}")
        return None

    return None


def main() -> None:
    st.title("Set Your Password")
    st.caption("Use this page from your Supabase invite link to activate your account and choose a password.")

    authenticated_user = _establish_password_setup_session()
    if not authenticated_user:
        st.info("Open this page using the invite or recovery link generated by Supabase.")
        return

    st.success(f"Preparing account setup for {authenticated_user.get('email', 'your account')}.")

    with st.form("set_password_form"):
        password = st.text_input("New Password", type="password", placeholder="Choose a strong password")
        password_confirm = st.text_input("Confirm Password", type="password", placeholder="Re-enter your password")
        submitted = st.form_submit_button("Save Password", type="primary", width="stretch")

    if not submitted:
        return

    if not password or not password_confirm:
        st.error("Enter your new password in both fields.")
        return

    if password != password_confirm:
        st.error("The passwords do not match.")
        return

    if len(password) < 12:
        st.error("Use a password with at least 12 characters.")
        return

    try:
        updated_user = update_authenticated_user_password(password)
        st.session_state["auth_user"] = updated_user
        st.success("Your password has been set. You can now return to the main app and sign in.")
        st.page_link("app.py", label="Open Pharm-Cal", icon=":material/open_in_new:")
    except Exception as exc:
        st.error(f"Could not save your password: {exc}")


if __name__ == "__main__":
    main()
